// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenCLI.Templates.WebAPI.Controllers
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using CodeGenCLI.CodeGenClasses;
    using CodeGenCLI.Extensions;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\dev\steffbeckers\code-generator\dotnet-angular\code-gen-cli\CodeGenCLI\Templates\WebAPI\Controllers\AuthControllerTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class AuthControllerTemplate : AuthControllerTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using AutoMapper;\r\nusing Microsoft.AspNetCore.Authorization;\r\nusing Microsoft.Asp" +
                    "NetCore.Mvc;\r\nusing Microsoft.Extensions.Configuration;\r\nusing Microsoft.Extensi" +
                    "ons.Logging;\r\nusing System.Threading.Tasks;\r\nusing ");
            
            #line 14 "C:\dev\steffbeckers\code-generator\dotnet-angular\code-gen-cli\CodeGenCLI\Templates\WebAPI\Controllers\AuthControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(!string.IsNullOrEmpty(config.WebAPI.NamespaceRoot) ? config.WebAPI.NamespaceRoot : config.Name));
            
            #line default
            #line hidden
            this.Write(".BLL;\r\nusing ");
            
            #line 15 "C:\dev\steffbeckers\code-generator\dotnet-angular\code-gen-cli\CodeGenCLI\Templates\WebAPI\Controllers\AuthControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(!string.IsNullOrEmpty(config.WebAPI.NamespaceRoot) ? config.WebAPI.NamespaceRoot : config.Name));
            
            #line default
            #line hidden
            this.Write(".Models;\r\nusing ");
            
            #line 16 "C:\dev\steffbeckers\code-generator\dotnet-angular\code-gen-cli\CodeGenCLI\Templates\WebAPI\Controllers\AuthControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(!string.IsNullOrEmpty(config.WebAPI.NamespaceRoot) ? config.WebAPI.NamespaceRoot : config.Name));
            
            #line default
            #line hidden
            this.Write(".ViewModels.Identity;\r\n\r\nnamespace ");
            
            #line 18 "C:\dev\steffbeckers\code-generator\dotnet-angular\code-gen-cli\CodeGenCLI\Templates\WebAPI\Controllers\AuthControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(!string.IsNullOrEmpty(config.WebAPI.NamespaceRoot) ? config.WebAPI.NamespaceRoot : config.Name));
            
            #line default
            #line hidden
            this.Write(".Controllers\r\n{\r\n    [Authorize]\r\n    [Route(\"api/[controller]\")]\r\n    [ApiContro" +
                    "ller]\r\n    public class AuthController : ControllerBase\r\n    {\r\n        private " +
                    "readonly IConfiguration configuration;\r\n        private readonly ILogger logger;" +
                    "\r\n        private readonly IMapper mapper;\r\n        private readonly AuthBLL bll" +
                    ";\r\n\r\n        /// <summary>\r\n        /// The constructor of the Auth controller.\r" +
                    "\n        /// </summary>\r\n        public AuthController(\r\n            IConfigurat" +
                    "ion configuration,\r\n            ILogger<AuthController> logger,\r\n            IMa" +
                    "pper mapper,\r\n            AuthBLL bll\r\n        )\r\n        {\r\n            this.co" +
                    "nfiguration = configuration;\r\n            this.logger = logger;\r\n            thi" +
                    "s.mapper = mapper;\r\n            this.bll = bll;\r\n        }\r\n\r\n        [HttpPost]" +
                    "\r\n        [Route(\"login\")]\r\n        [AllowAnonymous]\r\n        public async Task<" +
                    "ActionResult<AuthenticatedVM>> Login([FromBody] LoginVM loginVM)\r\n        {\r\n   " +
                    "         // Validation\r\n            if (!ModelState.IsValid)\r\n            {\r\n   " +
                    "             return BadRequest(ModelState);\r\n            }\r\n\r\n            Authen" +
                    "ticatedVM authenticatedVM = await this.bll.Login(loginVM);\r\n\r\n            return" +
                    " Ok(authenticatedVM);\r\n        }\r\n\r\n        [HttpGet]\r\n        [Route(\"logout\")]" +
                    "\r\n        public async Task<IActionResult> Logout()\r\n        {\r\n            awai" +
                    "t this.bll.Logout();\r\n\r\n            return Ok();\r\n        }\r\n\r\n        [HttpGet]" +
                    "\r\n        [Route(\"me\")]\r\n        public async Task<ActionResult<UserVM>> Me()\r\n " +
                    "       {\r\n            User currentUser = await this.bll.Me();\r\n\r\n            ret" +
                    "urn Ok(mapper.Map<User, UserVM>(currentUser));\r\n        }\r\n\r\n        [HttpPost]\r" +
                    "\n        [Route(\"register\")]\r\n        [AllowAnonymous]\r\n        public async Tas" +
                    "k<ActionResult<RegisteredVM>> Register([FromBody] RegisterVM registerVM)\r\n      " +
                    "  {\r\n            // Validation\r\n            if (!ModelState.IsValid)\r\n          " +
                    "  {\r\n                return BadRequest(ModelState);\r\n            }\r\n\r\n          " +
                    "  RegisteredVM registeredVM = await this.bll.Register(registerVM);\r\n\r\n          " +
                    "  return Ok(registeredVM);\r\n        }\r\n\r\n        [HttpGet]\r\n        [Route(\"conf" +
                    "irm-email\")]\r\n        [AllowAnonymous]\r\n        public async Task<ActionResult<E" +
                    "mailConfirmedVM>> ConfirmEmail([FromQuery] string id, [FromQuery] string code)\r\n" +
                    "        {\r\n            // Validation\r\n            if (!ModelState.IsValid || str" +
                    "ing.IsNullOrEmpty(id) || string.IsNullOrEmpty(code))\r\n            {\r\n           " +
                    "     return BadRequest(ModelState);\r\n            }\r\n\r\n            EmailConfirmed" +
                    "VM emailConfirmedVM = await this.bll.ConfirmEmail(id, code);\r\n\r\n            retu" +
                    "rn Ok(emailConfirmedVM);\r\n        }\r\n\r\n        [HttpPost]\r\n        [Route(\"forgo" +
                    "t-password\")]\r\n        [AllowAnonymous]\r\n        public async Task<IActionResult" +
                    "> ForgotPassword([FromBody] ForgotPasswordVM forgotPasswordVM)\r\n        {\r\n     " +
                    "       // Validation\r\n            if (!ModelState.IsValid)\r\n            {\r\n     " +
                    "           return BadRequest(ModelState);\r\n            }\r\n\r\n            await th" +
                    "is.bll.ForgotPassword(forgotPasswordVM);\r\n\r\n            return Ok();\r\n        }\r" +
                    "\n\r\n        [HttpPost]\r\n        [Route(\"reset-password\")]\r\n        [AllowAnonymou" +
                    "s]\r\n        public async Task<ActionResult<PasswordResettedVM>> ResetPassword([F" +
                    "romBody] ResetPasswordVM resetPasswordVM)\r\n        {\r\n            // Validation\r" +
                    "\n            if (!ModelState.IsValid)\r\n            {\r\n                return Bad" +
                    "Request(ModelState);\r\n            }\r\n\r\n            PasswordResettedVM passwordRe" +
                    "settedVM = await this.bll.ResetPassword(resetPasswordVM);\r\n\r\n            return " +
                    "Ok(passwordResettedVM);\r\n        }\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class AuthControllerTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
