// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGen.Templates.Projects.WebAPI.CodeGenOutput.API.Controllers
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using CodeGen.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class Controller : ControllerBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"using CodeGenOutput.API.DAL;
using CodeGenOutput.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CodeGenOutput.API.Controllers
{
    [Route(""api/");
            
            #line 18 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name.ToLower()));
            
            #line default
            #line hidden
            this.Write("s\")]\r\n    [ApiController]\r\n    public class ");
            
            #line 20 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name));
            
            #line default
            #line hidden
            this.Write("sController : ControllerBase\r\n    {\r\n        private readonly ApplicationDbContex" +
                    "t _context;\r\n\r\n        public ");
            
            #line 24 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name));
            
            #line default
            #line hidden
            this.Write("sController(ApplicationDbContext context)\r\n        {\r\n            _context = cont" +
                    "ext;\r\n        }\r\n\r\n        // GET: api/");
            
            #line 29 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name.ToLower()));
            
            #line default
            #line hidden
            this.Write("s\r\n        [HttpGet]\r\n        public async Task<ActionResult<IEnumerable<");
            
            #line 31 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name));
            
            #line default
            #line hidden
            this.Write(">>> Get");
            
            #line 31 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name));
            
            #line default
            #line hidden
            this.Write("s()\r\n        {\r\n            return await _context.");
            
            #line 33 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name));
            
            #line default
            #line hidden
            this.Write("s.ToListAsync();\r\n        }\r\n\r\n        // GET: api/");
            
            #line 36 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name.ToLower()));
            
            #line default
            #line hidden
            this.Write("s/{id}\r\n        [HttpGet(\"{id}\")]\r\n        public async Task<ActionResult<");
            
            #line 38 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name));
            
            #line default
            #line hidden
            this.Write(">> Get");
            
            #line 38 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name));
            
            #line default
            #line hidden
            this.Write("(Guid id)\r\n        {\r\n            var ");
            
            #line 40 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name.ToLower()));
            
            #line default
            #line hidden
            this.Write(" = await _context.");
            
            #line 40 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name));
            
            #line default
            #line hidden
            this.Write("s.FindAsync(id);\r\n\r\n            if (");
            
            #line 42 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name.ToLower()));
            
            #line default
            #line hidden
            this.Write(" == null)\r\n            {\r\n                return NotFound();\r\n            }\r\n\r\n  " +
                    "          return ");
            
            #line 47 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name.ToLower()));
            
            #line default
            #line hidden
            this.Write(";\r\n        }\r\n        \r\n        // POST: api/");
            
            #line 50 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name.ToLower()));
            
            #line default
            #line hidden
            this.Write("s\r\n        [HttpPost]\r\n        public async Task<ActionResult<");
            
            #line 52 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name));
            
            #line default
            #line hidden
            this.Write(">> Create");
            
            #line 52 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 52 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 52 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name.ToLower()));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            _context.");
            
            #line 54 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name));
            
            #line default
            #line hidden
            this.Write("s.Add(");
            
            #line 54 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name.ToLower()));
            
            #line default
            #line hidden
            this.Write(");\r\n            await _context.SaveChangesAsync();\r\n\r\n            return CreatedA" +
                    "tAction(\"Get");
            
            #line 57 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name));
            
            #line default
            #line hidden
            this.Write("\", new { id = ");
            
            #line 57 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name.ToLower()));
            
            #line default
            #line hidden
            this.Write(".Id }, ");
            
            #line 57 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name.ToLower()));
            
            #line default
            #line hidden
            this.Write(");\r\n        }\r\n\r\n        // PUT: api/");
            
            #line 60 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name.ToLower()));
            
            #line default
            #line hidden
            this.Write("s/{id}\r\n        [HttpPut(\"{id}\")]\r\n        public async Task<IActionResult> Updat" +
                    "e");
            
            #line 62 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name));
            
            #line default
            #line hidden
            this.Write("(Guid id, ");
            
            #line 62 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 62 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name.ToLower()));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            if (id != ");
            
            #line 64 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name.ToLower()));
            
            #line default
            #line hidden
            this.Write(".Id)\r\n            {\r\n                return BadRequest();\r\n            }\r\n\r\n     " +
                    "       _context.Entry(");
            
            #line 69 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name.ToLower()));
            
            #line default
            #line hidden
            this.Write(").State = EntityState.Modified;\r\n\r\n            try\r\n            {\r\n              " +
                    "  await _context.SaveChangesAsync();\r\n            }\r\n            catch (DbUpdate" +
                    "ConcurrencyException)\r\n            {\r\n                if (!");
            
            #line 77 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name));
            
            #line default
            #line hidden
            this.Write(@"Exists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // DELETE: api/");
            
            #line 90 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name.ToLower()));
            
            #line default
            #line hidden
            this.Write("s/{id}\r\n        [HttpDelete(\"{id}\")]\r\n        public async Task<IActionResult> De" +
                    "lete");
            
            #line 92 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name));
            
            #line default
            #line hidden
            this.Write("(Guid id)\r\n        {\r\n            var ");
            
            #line 94 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name.ToLower()));
            
            #line default
            #line hidden
            this.Write(" = await _context.");
            
            #line 94 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name));
            
            #line default
            #line hidden
            this.Write("s.FindAsync(id);\r\n            if (");
            
            #line 95 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name.ToLower()));
            
            #line default
            #line hidden
            this.Write(" == null)\r\n            {\r\n                return NotFound();\r\n            }\r\n\r\n  " +
                    "          _context.");
            
            #line 100 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name));
            
            #line default
            #line hidden
            this.Write("s.Remove(");
            
            #line 100 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name.ToLower()));
            
            #line default
            #line hidden
            this.Write(");\r\n            await _context.SaveChangesAsync();\r\n\r\n            return NoConten" +
                    "t();\r\n        }\r\n\r\n        private bool ");
            
            #line 106 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name));
            
            #line default
            #line hidden
            this.Write("Exists(Guid id)\r\n        {\r\n            return _context.");
            
            #line 108 "C:\Dev\steffbeckers\code-generator\dotnet\CodeGen\Templates\Projects\WebAPI\CodeGenOutput.API\Controllers\Controller.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.Name));
            
            #line default
            #line hidden
            this.Write("s.Any(e => e.Id == id);\r\n        }\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class ControllerBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
